### ISSUE TITLE
求教，使用命令行运行代码出现“model not loaded”

### ISSUE THREAD

**Issue by norahfung** [iris2hu/Chinese-collocation-complexity#1]
使用pycharm可以成功加载pyltp的model并运行其他代码，但使用命令行运行胡老师的这个代码出现了很多“model not loaded”，请问老师，这该如何解决呢？

**Comment by iris2hu** [comment]
> python main.py -i ./samples/ -o result.csv -mp path_to_LTP_models

path_to_LTP_models 为LTP模型路径，需要指定。

**Comment by norahfung** [comment]
问题已解决，谢谢老师！
